src/Entity/User.php
<?php

namespace App\Entity;

use App\Entity\Trait\CreatedAtTrait;
use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['username'], message: 'There is already an account with this username')]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    use CreatedAtTrait;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $username = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 100)]
    private ?string $lastname = null;

    #[ORM\Column(length: 100)]
    private ?string $firstname = null;

    #[ORM\Column(length: 255)]
    private ?string $address = null;

    #[ORM\Column(length: 5)]
    private ?string $zipcode = null;

    #[ORM\Column(length: 150)]
    private ?string $city = null;

    #[ORM\Column]
    private ?bool $is_verified = false;

    #[ORM\Column(length: 100, nullable: true)]
    private ?string $resetToken = null;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Orders::class)]
    private Collection $orders;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Comment::class)]
    private Collection $comments;

    public function __construct(?string $username = null)
    {
        $this->username = $username;
        $this->comments = new ArrayCollection();
        $this->orders = new ArrayCollection();
        $this->created_at = new \DateTimeImmutable();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->username;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getZipcode(): ?string
    {
        return $this->zipcode;
    }

    public function setZipcode(string $zipcode): self
    {
        $this->zipcode = $zipcode;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getIsVerified(): ?bool
    {
        return $this->is_verified;
    }

    public function setIsVerified(bool $is_verified): self
    {
        $this->is_verified = $is_verified;

        return $this;
    }

    public function getResetToken(): ?string
    {
        return $this->resetToken;
    }

    public function setResetToken(string $resetToken): self
    {
        $this->resetToken = $resetToken;

        return $this;
    }

    /**
     * @return Collection<int, Orders>
     */
    public function getOrders(): Collection
    {
        return $this->orders;
    }

    public function addOrder(Orders $order): self
    {
        if (!$this->orders->contains($order)) {
            $this->orders->add($order);
            $order->setUser($this);
        }

        return $this;
    }

    public function removeOrder(Orders $order): self
    {
        if ($this->orders->removeElement($order)) {
            // set the owning side to null (unless already changed)
            if ($order->getUser() === $this) {
                $order->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setUser($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getUser() === $this) {
                $comment->setUser(null);
            }
        }

        return $this;
    }
}

src/Controller/Ecommerce/Admin/CategoriesController.php
<?php

namespace App\Controller\Ecommerce\Admin;

use App\Entity\Categories;
use App\Form\CategoriesFormType;
use App\Repository\CategoriesRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\String\Slugger\SluggerInterface;

#[Route('/ecommerce/admin/categories', name: 'admin_categories_')]
class CategoriesController extends AbstractController
{
    #[Route('/', name: 'index')]
    public function index(CategoriesRepository $categoriesRepository):Response
    {
        $categories = $categoriesRepository->findBy([], ['categoryOrder' => 'asc']);
        return $this->render('Ecommerce/admin/categories/index.html.twig', [
            'categories' => $categories
        ]);
    }

    #[Route('/ajout', name: 'add')]
    public function add(Request $request, EntityManagerInterface $entityManager, SluggerInterface $slugger): Response
    {
        $this->denyAccessUnlessGranted('ROLE_ADMIN');

        $category = new Categories();

        $form = $this->createForm(CategoriesFormType::class, $category);

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid())
        {
            $slug = $slugger->slug($category->getName())->lower();
            $category->setSlug($slug);

            // Récupération de l'entier maximum dans la colonne categoryOrder
            $queryBuilder = $entityManager->createQueryBuilder();
            $queryBuilder->select('MAX(c.categoryOrder)')
                ->from(Categories::class, 'c');
            $maxCategoryOrder = $queryBuilder->getQuery()->getSingleScalarResult() ?? 0;

            // Incrémentation de l'entier
            $categoryOrder = $maxCategoryOrder + 1;

            // Attribution de la valeur de l'entier à la propriété categoryOrder de l'objet Category
            $category->setCategoryOrder($categoryOrder);
            $category->setProductCount('0');

            $entityManager->persist($category);
            $entityManager->flush();

            $this->addFlash('success', 'Catégorie ajouté avec succès');

            return $this->redirectToRoute('admin_categories_index');
        }

        return $this->render('Ecommerce/admin/categories/add.html.twig', [
            'form' => $form->createView()
        ]);
    }

    #[Route('/edition/{id}', name: 'edit')]
    public function edit(Categories $categories, Request $request, EntityManagerInterface $entityManager, SluggerInterface $slugger): Response
    {
        $this->denyAccessUnlessGranted('CATEGORIES_EDIT', $categories);

        $form = $this->createForm(CategoriesFormType::class, $categories);

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid())
        {
            $slug = $slugger->slug($categories->getName())->lower();
            $categories->setSlug($slug);

            $entityManager->persist($categories);
            $entityManager->flush();

            $this->addFlash('success', 'Catégorie modifier avec succès');

            return $this->redirectToRoute('admin_categories_index');
        }

        return $this->render('Ecommerce/admin/categories/edit.html.twig', [
            'form' => $form->createView(),
        ]);
    }

}

src/Controller/Ecommerce/Admin/MainController.php
<?php

namespace App\Controller\Ecommerce\Admin;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/ecommerce/admin', name: 'admin_')]
class MainController extends AbstractController
{
    #[Route('/', name: 'index')]
    public function index():Response
    {
        return $this->render('Ecommerce/admin/index.html.twig');
    }
}

src/Controller/Ecommerce/Admin/OrdersController.php
<?php

namespace App\Controller\Ecommerce\Admin;

use App\Repository\OrdersRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/ecommerce/admin/commandes', name: 'admin_orders_')]
class OrdersController extends AbstractController
{
    #[Route('/', name: 'index')]
    public function orders(OrdersRepository $ordersRepository, EntityManagerInterface $entityManager): Response
    {
        $orders = $ordersRepository->findBy([], ['created_at' => 'DESC']);
        $ordersDetails = [];

        foreach ($orders as $order)
        {
            $dql = "SELECT od FROM App\Entity\OrdersDetails od WHERE od.orders = :orders";
            $query = $entityManager->createQuery($dql);
            $query->setParameter('orders', $order);
            $details = $query->getResult();

            $ordersDetails[$order->getId()] = $details;
        }

        return $this->render('Ecommerce/admin/orders/index.html.twig', [
            'orders' => $orders,
            'ordersDetails' => $ordersDetails
        ]);
    }
}

src/Controller/Ecommerce/Admin/ProductsController.php
<?php

namespace App\Controller\Ecommerce\Admin;

use App\Entity\Images;
use App\Entity\Products;
use App\Form\ProductsFormType;
use App\Repository\ProductsRepository;
use App\Service\PictureService;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\String\Slugger\SluggerInterface;

#[Route('/ecommerce/admin/produits', name: 'admin_products_')]
class ProductsController extends AbstractController
{
    #[Route('/', name: 'index')]
    public function index(ProductsRepository $productsRepository): Response
    {
        $produits = $productsRepository->findAll();

        return $this->render('Ecommerce/admin/products/index.html.twig', [
            'produits' => $produits
        ]);
    }

    #[Route('/ajout', name: 'add')]
    public function add(Request $request, EntityManagerInterface $entityManager, SluggerInterface $slugger, PictureService $pictureService): Response
    {
        $this->denyAccessUnlessGranted('ROLE_ADMIN');

        $product = new Products();

        $productForm = $this->createForm(ProductsFormType::class, $product);

        $productForm->handleRequest($request);

        if($productForm->isSubmitted() && $productForm->isValid())
        {
            $images = $productForm->get('images')->getData();

            foreach($images as $image)
            {
                $folder = 'products';

                $fichier = $pictureService->add($image, $folder, 300, 300);

                $img = new Images();
                $img->setName($fichier);
                $product->addImage($img);
            }

            $slug = $slugger->slug($product->getName());
            $product->setSlug($slug->lower());

//            $prix = $product->getPrice() * 100;
//            $product->setPrice($prix);

            $entityManager->persist($product);
            $entityManager->flush();

            $this->addFlash('success', 'Produit ajouté avec succès');

            return $this->redirectToRoute('admin_products_index');
        }

        return $this->render('Ecommerce/admin/products/add.html.twig', [
            'productForm' => $productForm->createView()
        ]);
    }

    #[Route('/edition/{id}', name: 'edit')]
    public function edit(Products $products, Request $request, EntityManagerInterface $entityManager, SluggerInterface $slugger, PictureService $pictureService): Response
    {
        $this->denyAccessUnlessGranted('PRODUCT_EDIT', $products);

//        $prix = $products->getPrice() / 100;
//        $products->setPrice($prix);

        $productForm = $this->createForm(ProductsFormType::class, $products);

        $productForm->handleRequest($request);

        if($productForm->isSubmitted() && $productForm->isValid())
        {
            $images = $productForm->get('images')->getData();

            foreach($images as $image)
            {
                $folder = 'products';

                $fichier = $pictureService->add($image, $folder, 300, 300);

                $img = new Images();
                $img->setName($fichier);
                $products->addImage($img);
            }

            $slug = $slugger->slug($products->getName());
            $products->setSlug($slug->lower());

//            $prix = $products->getPrice() * 100;
//            $products->setPrice($prix);

            $entityManager->persist($products);
            $entityManager->flush();

            $this->addFlash('success', 'Produit modifier avec succès');

            return $this->redirectToRoute('admin_products_index');
        }

        return $this->render('Ecommerce/admin/products/edit.html.twig', [
            'productForm' => $productForm->createView(),
            'product' => $products
        ]);
    }

    #[Route('/suppression/{id}', name: 'delete')]
    public function delete(Products $products): Response
    {
        $this->denyAccessUnlessGranted('PRODUCT_DELETE', $products);
        return $this->render('Ecommerce/admin/products/index.html.twig', [

        ]);
    }

    #[Route('/suppression/image/{id}', name: 'delete_image', methods: ['DELETE'])]
    public function deleteImage(Images $images, Request $request, EntityManagerInterface $entityManager, PictureService $pictureService): JsonResponse
    {
        $data = json_decode($request->getContent(), true);

        if($this->isCsrfTokenValid('delete'.$images->getId(), $data['_token']))
        {
            $nom = $images->getName();

            if($pictureService->delete($nom, 'products', 300, 300))
            {
                $entityManager->remove($images);
                $entityManager->flush();

                return new JsonResponse(['success' => true], 200);
            }

            return new JsonResponse(['error' => 'Erreur de suppression'], 400);
        }

        return new JsonResponse(['error' => 'Token invalide'], 400);
    }
}

templates/Ecommerce/profile/edit.html.twig
{% extends 'Ecommerce/base.html.twig' %}

{% block title %}Modification du profil{% endblock %}

{% block body %}
    {% include 'Ecommerce/_partials/_header.html.twig' with {'titre': 'Modifier mes informations'} %}
    <main class="container">
        <section class="row">
            <div class="col-12">
                {{ form_start(form) }}
                {{ form_row(form.email) }}
                {{ form_row(form.username, {'label': 'Nom d\'utilisateur'}) }}
                {{ form_row(form.lastname, {'label': 'Nom'}) }}
                {{ form_row(form.firstname, {'label': 'Prénom'}) }}
                {{ form_row(form.address, {'label': 'Adresse'}) }}
                {{ form_row(form.zipcode, {'label': 'Code postal'}) }}
                {{ form_row(form.city, {'label': 'Ville'}) }}
                <button type="submit" class="btn btn-primary">Modifier</button>
                {{ form_end(form) }}
            </div>
        </section>
    </main>
{% endblock %}

templates/Ecommerce/profile/editpassword.html.twig
{% extends 'Ecommerce/base.html.twig' %}

{% block title %}Modification du mot de passe{% endblock %}

{% block body %}
    {% include 'Ecommerce/_partials/_header.html.twig' with {'titre': 'Modifier mon mot de passe'} %}
    <main class="container">
        <section class="row">
            <div class="col-12">
                <form method="post">
                    <div class="mb-3">
                        <label for="pass" class="form-label">Mot de passe</label>
                        <input type="password" id="pass" name="pass" class="form-control">
                    </div>
                    <div class="mb-3">
                        <label for="pass2" class="form-label">Confirmer le mot de passe</label>
                        <input type="password" id="pass2" name="pass2" class="form-control">
                    </div>
                    <button type="submit" class="btn btn-primary">Modifier</button>
                </form>
            </div>
        </section>
    </main>
{% endblock %}

templates/Ecommerce/profile/index.html.twig
{% extends 'Ecommerce/base.html.twig' %}

{% block title %}Mon profil{% endblock %}

{% block body %}
    {% include 'Ecommerce/_partials/_header.html.twig' with {'titre': 'Mes informations'} %}
    <main class="container">
        <section class="row">
            <div class="col-6">
                <p>Email :</p>
                <p>Nom :</p>
                <p>Prénom :</p>
                <p>Adresse :</p>
                <p>Code postal :</p>
                <p>Ville :</p>
                <p>Compte vérifié :</p>
            </div>
            <div class="col-6">
                <p>{{ app.user.email }}</p>
                <p>{{ app.user.lastname }}</p>
                <p>{{ app.user.firstname }}</p>
                <p>{{ app.user.address }}</p>
                <p>{{ app.user.zipcode }}</p>
                <p>{{ app.user.city }}</p>
                <div class="custom-control custom-switch">
                    <input class="custom-control-input" type="checkbox" id="switch{{ app.user.id }}" {{ app.user.isVerified ? 'checked' : '' }} disabled>
                    <label class="custom-control-label" for="switch{{ app.user.id }}"></label>
                </div>
            </div>
            <div class="col-12 text-center">
                <a href="{{ path('profile_edit') }}" class="btn btn-primary">Modifier mon profil</a>
                <a href="{{ path('profile_edit_password') }}" class="btn btn-primary">Modifier mon mot de passe</a>
            </div>
        </section>
    </main>
{% endblock %}

templates/Ecommerce/profile/orders.html.twig
{% extends 'Ecommerce/base.html.twig' %}

{% block title %}Mon profil{% endblock %}

{% block body %}
    {% include 'Ecommerce/_partials/_header.html.twig' with {'titre': 'Mes commandes'} %}
    <main class="container">
        <section class="row">

            {% for order in orders %}
                <div class="col-12">
                    <table class="table">
                        <thead>
                        <tr>
                            <th>Date de la commande :</th>
                            <th>Référence :</th>
                            <th>Détails de la commande :</th>
                        </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td class="align-middle">{{ order.createdAt|date("d/m/Y H:i:s") }}</td>
                                <td class="align-middle">{{ order.reference }}</td>
                                <td class="align-middle">
                                    <a class="btn btn-primary" data-toggle="collapse" href="#showOrdersDetails{{ order.id }}" role="button" aria-expanded="false" aria-controls="showOrdersDetails{{ order.id }}">Voir</a>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                    <div class="collapse multi-collapse" id="showOrdersDetails{{ order.id }}">
                        <div class="card card-body">
                            {% set total = 0 %}
                            {% for details in ordersDetails[order.id] %}
                                {% set total = total + details.price %}
                                Produit : {{ details.products.name }}
                                </br>
                                Quantité : {{ details.quantity }}
                                </br>
                                Prix : {{ details.price / 100 }}€
                                {% if loop.last == false %}
                                    <hr>
                                {% endif %}
                            {% endfor %}
                            <div class="bg-light text-center m-3">
                                Total : {{ total / 100 }}€
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </section>
    </main>
{% endblock %}